# 01. Знакомство с `torch.Tensor`

V 0.1 04.02.2021

---

При решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использование функционала библиотеки `torch`.

[PyTorch documentation](https://pytorch.org/docs/stable/#pytorch-documentation)

In [792]:
import torch
import numpy as np
import math

## 1.1 Создание тензоров и выполнение базовых операций над ними

[Документация по функциям для создания тензоров](https://pytorch.org/docs/stable/torch.html#creation-ops)

[Документация по функциям для работы с индексами](https://pytorch.org/docs/stable/torch.html#indexing-slicing-joining-mutating-ops)

1.1.1 Создайте двумерный тензор размера (8, 8). Используя как можно меньше операций, добейтесь расстановки кодов "шахматных фигур".

Ожидаемый результат:

```
[[-4., -3., -2., -6., -5., -2., -3., -4.],
 [-1., -1., -1., -1., -1., -1., -1., -1.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [0., 0., 0., 0., 0., 0., 0., 0.],
 [1., 1., 1., 1., 1., 1., 1., 1.],
 [4., 3., 2., 6., 5., 2., 3., 4.]]
```

In [64]:
#Я пытался сделать через cat/concat, c генерацией нулей размером 4,8 но cat работать не захотел
high_rankes = torch.tensor([4., 3., 2., 6., 5., 2., 3., 4.])
ones = torch.ones(8)
zeros = torch.zeros(8)
torch.stack((-high_rankes, -ones, zeros, zeros, zeros, zeros, ones, high_rankes), 0)

tensor([[-4., -3., -2., -6., -5., -2., -3., -4.],
        [-1., -1., -1., -1., -1., -1., -1., -1.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
        [ 4.,  3.,  2.,  6.,  5.,  2.,  3.,  4.]])

1.1.2 Средствами `torch` рассчитать произведения четных чисел от 2 до 20 на ближайшие к ним бОльшие нечетные числа.

In [68]:
torch.arange(2, 22, 2) * torch.arange(3, 23, 2)

tensor([  6,  20,  42,  72, 110, 156, 210, 272, 342, 420])

1.1.3 Создать тензор размера 11x7 вида: [[1, 2, 3, ..., 7], [11, 12, 13, ..., 17], [21, 22, 23, ..., 27], ..., [101, 102, 103, ..., 107]]

In [225]:
torch.arange(1, 111, 1).reshape(11, 10)[:, :7]

tensor([[  1,   2,   3,   4,   5,   6,   7],
        [ 11,  12,  13,  14,  15,  16,  17],
        [ 21,  22,  23,  24,  25,  26,  27],
        [ 31,  32,  33,  34,  35,  36,  37],
        [ 41,  42,  43,  44,  45,  46,  47],
        [ 51,  52,  53,  54,  55,  56,  57],
        [ 61,  62,  63,  64,  65,  66,  67],
        [ 71,  72,  73,  74,  75,  76,  77],
        [ 81,  82,  83,  84,  85,  86,  87],
        [ 91,  92,  93,  94,  95,  96,  97],
        [101, 102, 103, 104, 105, 106, 107]])

1.1.4 Написать функцию, которая для целых значений `n` и `m` будет возвращать тензор размера `n`x`m`, заполненный текстурой размера 2x2, состоящей из следующих значений:

```
0 1

2 3

```

Пример для n = 4 и m = 5:

```
0 1 0 1 0

2 3 2 3 2

0 1 0 1 0

2 3 2 3 2
```

In [157]:
def make_texture(n: int, m: int) -> torch.LongTensor:
    return torch.tensor([[0, 1],[2, 3]]).tile(round(n / 2 + 1),round(m / 2 + 1))[ : n, : m]

make_texture(4, 5)  

tensor([[0, 1, 0, 1, 0],
        [2, 3, 2, 3, 2],
        [0, 1, 0, 1, 0],
        [2, 3, 2, 3, 2]])

1.1.5 Сгенерировать двумерный тензор `t` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в дипазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида $ax+b$ так, что после нормализации максимальный элемент масива будет равен 1.0, минимальный 0.0

tensor([[0.3974, 0.9777, 0.4236, 0.5684, 0.9566, 0.0672, 0.4254],
        [0.6465, 0.0796, 0.6333, 0.7629, 0.0804, 0.4157, 0.9299],
        [0.0619, 0.4911, 0.6061, 1.0000, 0.4029, 0.8861, 0.6457],
        [0.8274, 0.0071, 0.0000, 0.8428, 0.7036, 0.3521, 0.2053]])

In [179]:
torch.randint(0, 21, (4, 7)) * 0.05 
#я возможно не правильно понял задачу?
#не очень понимаю почему в примере результата такие странные цифры после запятой
# ax + b = y; a = 0.05 - т.е. 1/20. смещение b нам тут не нужно поэтому берем его = 0


tensor([[0.1500, 0.9000, 0.3000, 0.4000, 0.6500, 0.7500, 0.5500],
        [0.4500, 0.6500, 0.8000, 1.0000, 0.4000, 0.1500, 0.2000],
        [0.0500, 0.4500, 0.0500, 0.6000, 0.0000, 0.8500, 0.5500],
        [0.6500, 0.2500, 0.9000, 0.2500, 0.1500, 0.5500, 0.1000]])

[Random Sampling](https://pytorch.org/docs/stable/torch.html#random-sampling)

[Distributions](https://pytorch.org/docs/stable/distributions.html)

1.1.6 Задать два двумерных тензора `ar1` и `ar2` размерности (4, 7), состоящих из случайных целых чисел в пределах от 0 до 10. Построить двумерный тензор размерности (4, 7), каждый элемент которого представляет собой максимум из двух значений, находящихся на аналогичной позиции в тензорах `ar1`, `ar2`.

[Reductions ops](https://pytorch.org/docs/stable/torch.html#reduction-ops)

In [182]:
ar1 = torch.randint(0, 11, (4, 7))
ar2 = torch.randint(0, 11, (4, 7))
torch.where(ar1 > ar2, ar1, ar2)

tensor([[ 5,  6,  6,  5, 10,  9,  1],
        [10, 10,  4, 10,  6, 10,  9],
        [ 1,  8,  4,  8,  6,  5,  9],
        [ 5, 10,  7,  4,  8,  4,  9]])

1.1.7 Создать тензор из 20 случайных целых чисел от 0 до 100. Получить второе сверху значение в тензоре. Определить индекс этого значения.

In [221]:
tensor = torch.randint(0, 101, (1, 20))
print('index: ' + str(tensor.argsort()[:, -2:-1].item()))
print('value: ' + str(tensor[0, tensor.argsort()[:, -2:-1]].item()))

index: 18
value: 96


## 1.2 Распространение

[Numpy broadcasting](https://numpy.org/devdocs/user/theory.broadcasting.html)

[Torch broadcasting](https://pytorch.org/docs/stable/notes/broadcasting.html)

1.2.1 Создать тензор 11x7 вида: `[[1, 2, 3, ..., 7], [11, 12, 13, ..., 17], [21, 22, 23, ..., 27], ..., [101, 102, 103, ..., 107]]`. При решении задачи применить технику распространения.

In [251]:
a = torch.arange(1, 8, 1)
b = torch.arange(0, 110, 10).reshape(11,1)

a + b

tensor([[  1,   2,   3,   4,   5,   6,   7],
        [ 11,  12,  13,  14,  15,  16,  17],
        [ 21,  22,  23,  24,  25,  26,  27],
        [ 31,  32,  33,  34,  35,  36,  37],
        [ 41,  42,  43,  44,  45,  46,  47],
        [ 51,  52,  53,  54,  55,  56,  57],
        [ 61,  62,  63,  64,  65,  66,  67],
        [ 71,  72,  73,  74,  75,  76,  77],
        [ 81,  82,  83,  84,  85,  86,  87],
        [ 91,  92,  93,  94,  95,  96,  97],
        [101, 102, 103, 104, 105, 106, 107]])

1.2.2 Вычесть одномерный тензор `b_1d` из двухмерного тензора `a_2d`, так, чтобы каждый элемент одномерного тензора вычитался из всех элементов соответствующих строк двумерного тензора.

_Пример:_

Для входа:
```python
a_2d = torch.tensor([[3,3,3],[4,4,4],[5,5,5]])
b_1d = torch.tensor([1,2,3])
```

Ожидается резульат:

```python
[[2 2 2]
 [2 2 2]
 [2 2 2]]
```

In [253]:
a_2d = torch.tensor([[3,3,3],[4,4,4],[5,5,5]])
b_1d = torch.tensor([1,2,3]).reshape(3, 1)

a_2d - b_1d

tensor([[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]])

## 1.3 Индексы, маскирование и прихотливое индексирование

[Документация по функциям для работы с индексами](https://pytorch.org/docs/stable/torch.html#indexing-slicing-joining-mutating-ops)

1.3.1 Получить индексы, для которых элементы тензоров `a` и `b` совпадают.

_Пример:_

Для входа:
```python
a = torch.tensor([1,2,3,2,3,4,3,4,5,6])
b = torch.tensor([7,2,10,2,7,4,9,4,9,8])
```

Ожидается резульат:

```python
tensor([1, 3, 5, 7])
```

tensor([0, 1, 0, 1, 0, 1, 0, 1, 0, 0])


tensor([5, 1, 7, 3])

In [255]:
a = torch.tensor([1,2,3,2,3,4,3,4,5,6])
b = torch.tensor([7,2,10,2,7,4,9,4,9,8])

torch.where(a == b) #так можно делать?

(tensor([1, 3, 5, 7]),)

1.3.2 Инвертировать порядок элементов в двумерном тензоре `torch.arange(9).view(3,3)`.

Ожидаемый результат:


```python
tensor([[8, 7, 6],
       [5, 4, 3],
       [2, 1, 0]])
```

In [267]:
torch.arange(9).view(3,3).reshape(1, 9).sort(descending=True).values.reshape(3, 3)

tensor([[8, 7, 6],
        [5, 4, 3],
        [2, 1, 0]])

1.3.3 Из входного тензора a получить только элементы, находящиеся в диапазоне от 5 до 10.

_Пример:_

Для входа:
```python
a = torch.tensor([2, 6, 1, 9, 10, 3, 27])
```

Ожидается результат:

```python
tensor([6, 9, 10])
```

In [283]:
a = torch.tensor([2, 6, 1, 9, 10, 3, 27])
a = a.masked_select(a >= 5)
a.masked_select(a <= 10)

tensor([ 6,  9, 10])

1.3.4 Поменять местами столбец 1 и 2 тензора `torch.arange(9).reshape(3,3)`

In [324]:
tensor = torch.arange(9).reshape(3,3)

splited_tensors = torch.split(tensor, 1, 1)
torch.cat((splited_tensors[0], splited_tensors[2], splited_tensors[1]), 1)

tensor([[0, 2, 1],
        [3, 5, 4],
        [6, 8, 7]])

1.3.5 Создать тензор 8 на 10 из случайных целых чисел из диапазона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [351]:
tensor = torch.randint(0, 11, (8, 10))
print(tensor)
index = torch.cumsum(tensor, 1)[:, -1 :].sort(0)[1][0]
print('min index: ' + str(index))
print('min string: ' + str(tensor[index]))

tensor([[ 7,  8, 10,  1,  1,  7,  4,  5,  8,  7],
        [10,  2,  1,  2,  9,  6,  8,  9,  2,  6],
        [10,  3,  6,  3,  4,  8,  0,  7,  5,  9],
        [ 9,  1,  9, 10,  5,  2,  8,  4,  2,  3],
        [ 8,  4,  6,  3,  0,  8,  7,  1, 10, 10],
        [ 9,  5,  0,  0,  9,  0,  1,  1, 10,  0],
        [ 1,  2,  1,  1,  7,  7,  1,  5,  4, 10],
        [ 2,  9,  0, 10,  1,  1, 10,  9,  1,  3]])
min index: tensor([5])
min string: tensor([[ 9,  5,  0,  0,  9,  0,  1,  1, 10,  0]])


1.3.6 Cоздать тензор из 20 случайных целых чисел от 0 до 100. Обрезать значения тензора (заменить значения, выходящие за диапазон, на крайние значения) снизу по значению 30, сверху по значению 70.

In [363]:
tensor = torch.randint(0, 101, (1, 20))
print('Generated tensor:')
print(tensor)
tensor = tensor.apply_((lambda x: 70 if(x >= 70) else x))
tensor = tensor.apply_((lambda x: 30 if(x <= 30) else x))
print('Values trimmed tensor:')
print(tensor)

Generated tensor:
tensor([[ 11,  50,  65,  45,  63,  34,  48,  53,  25,  69,  87,   1,  57,  29,
          16, 100,  84,  13,  94,  22]])
Values trimmed tensor:
tensor([[30, 50, 65, 45, 63, 34, 48, 53, 30, 69, 70, 30, 57, 30, 30, 70, 70, 30,
         70, 30]])


1.3.7 Создать два тензора размера 30 на 3 из случайных целых чисел из диапазона от 0 до 10 и найти все значения первого тензора, которые больше соответсвующих (по расположению) значений второго тензора. Подсчитать сумму этих значений.

In [365]:
tensor_1 = torch.randint(0, 11, (30, 3))
tensor_2 = torch.randint(0, 11, (30, 3))

torch.where(tensor_1 > tensor_2, tensor_1, torch.zeros(30,3)).sum()

tensor(285.)

1.3.8 При помощи прихотливого индексирования для двухмерного массива размерности (20, 20), состоящего из случайных целых чисел в пределах от 0 до 10 получить массив элементов находящихся на диагонали, проходящей над основной диагональю.

In [370]:
tensor = torch.randint(0, 11, (20, 20))
torch.diagonal(tensor[: , 1: ])

tensor([ 3,  3,  6,  7,  8, 10, 10,  6,  5, 10,  0,  5,  8,  0,  9, 10,  5,  2,
         6])

1.3.9 Задать два двухмерных тензора `ar1` и `ar2` размерности (5, 10), состоящих из случайных целых чисел в пределах от 0 до 10. Удвоить все значения `ar1`, которые совпадают со значениями `ar2`, расположенными на аналогичных позициях.

In [374]:
ar1 = torch.randint(0, 11, (5, 10))
ar2 = torch.randint(0, 11, (5, 10))

torch.where(ar1 == ar2, ar1*2, ar1)

tensor([[ 2, 20, 10,  5,  2,  5,  3,  7,  4,  6],
        [ 2,  2,  5,  4,  9,  1, 16, 16, 18,  6],
        [ 6,  4,  2,  6,  5,  2,  6,  7,  4,  8],
        [ 8, 10,  2,  5,  8, 10,  3,  1,  3,  5],
        [ 4,  9,  2,  8,  3,  4,  5, 10,  8,  1]])

1.3.10 Заданы три двухмерных тензора `ar1`, `ar2` и `ar3` размерности (4, 7), состоящие из случайных целых чисел в пределах от 0 до 10. Обнулить все элементы `ar1`, которые больше соответствующих (находящихся в соответствующих позициях) элементов `ar2` и меньше соответствующих элементов `ar3`.

In [389]:
ar1 = torch.randint(0, 11, (4, 7))
ar2 = torch.randint(0, 11, (4, 7))
ar3 = torch.randint(0, 11, (4, 7))

torch.where((ar1 - ar2) * (ar3 - ar1) > 0, torch.zeros(4,7), ar1)

tensor([[ 1., 10.,  3.,  6.,  0.,  1.,  0.],
        [ 7.,  6.,  7.,  0.,  7.,  7.,  9.],
        [ 0.,  0.,  0.,  0.,  6.,  0.,  5.],
        [ 9.,  7.,  0.,  7.,  4.,  7., 10.]])

1.3.11 Задан двумерный тензор `ar1` размерности (20, 5), состоящий из случайных целых чисел в пределах от 0 до 20. Определить, в каких столбцах не менее 5 раз встречается значение, максимальное по своей строке.

In [491]:
###########
# Не получилось
###########
tensor = torch.randint(0, 21, (20, 5))

print(tensor)

max_row_values = torch.sort(tensor)[0][ :, -1: ]

result = torch.where(tensor == max_row_values, tensor, torch.zeros(20, 5))
print(result)
result.unique(return_counts=True, dim = 0)



#print(torch.where(tensor[-1:] == tensor[: 1]))
#print(tensor)
#print(tensor[-1:])
#print(tensor[: 1])


tensor([[ 8,  4, 13, 15,  9],
        [ 0, 11, 11,  1, 20],
        [ 9, 10,  3, 18,  6],
        [10,  7,  2, 12,  3],
        [11,  0,  4, 10, 18],
        [ 8, 15, 12,  7, 10],
        [20, 11, 13, 17,  8],
        [16,  9, 10,  8, 16],
        [15,  9, 17, 12, 15],
        [18,  2, 19, 17, 11],
        [13,  5, 19, 16, 10],
        [ 8, 12, 13,  2, 12],
        [10, 15,  2, 17, 10],
        [16, 17, 10, 17, 14],
        [ 9, 19, 15, 13,  7],
        [ 0, 17, 19, 10,  4],
        [14,  6,  5, 13, 11],
        [ 5, 11,  7,  4, 13],
        [20, 19,  0, 10, 16],
        [ 5, 15, 12,  9,  8]])
tensor([[ 0.,  0.,  0., 15.,  0.],
        [ 0.,  0.,  0.,  0., 20.],
        [ 0.,  0.,  0., 18.,  0.],
        [ 0.,  0.,  0., 12.,  0.],
        [ 0.,  0.,  0.,  0., 18.],
        [ 0., 15.,  0.,  0.,  0.],
        [20.,  0.,  0.,  0.,  0.],
        [16.,  0.,  0.,  0., 16.],
        [ 0.,  0., 17.,  0.,  0.],
        [ 0.,  0., 19.,  0.,  0.],
        [ 0.,  0., 19.,  0.,  0.],
        [ 0., 

(tensor([[ 0.,  0.,  0.,  0., 13.],
         [ 0.,  0.,  0.,  0., 18.],
         [ 0.,  0.,  0.,  0., 20.],
         [ 0.,  0.,  0., 12.,  0.],
         [ 0.,  0.,  0., 15.,  0.],
         [ 0.,  0.,  0., 17.,  0.],
         [ 0.,  0.,  0., 18.,  0.],
         [ 0.,  0., 13.,  0.,  0.],
         [ 0.,  0., 17.,  0.,  0.],
         [ 0.,  0., 19.,  0.,  0.],
         [ 0., 15.,  0.,  0.,  0.],
         [ 0., 17.,  0., 17.,  0.],
         [ 0., 19.,  0.,  0.,  0.],
         [14.,  0.,  0.,  0.,  0.],
         [16.,  0.,  0.,  0., 16.],
         [20.,  0.,  0.,  0.,  0.]]),
 tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 2, 1, 1, 1, 1, 2]))

1.3.12 Задан двумерный тензор `ar1` размерности (4, 7), состоящий из случайных  чисел в пределах от 0 до 1. Обнулить все значения в массиве, расположенные строго правее и ниже максимального элемента массива. 

In [744]:
ar1 = torch.rand((4, 7))
max_element_index_1d = int(ar1.argmax()) + 1
y = math.floor(max_element_index_1d/7)
x = max_element_index_1d - (y) * 7
zeros = torch.zeros((int(4 - y), int(7 - x)))
ar1[y: , x: ] = zeros

ar1

tensor([[0.4336, 0.3529, 0.2647, 0.9019, 0.3721, 0.2706, 0.2600],
        [0.8338, 0.3960, 0.1362, 0.7910, 0.7072, 0.0864, 0.0872],
        [0.8703, 0.2833, 0.9879, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.7981, 0.1741, 0.7365, 0.0000, 0.0000, 0.0000, 0.0000]])

1.3.13 Построить "one-hot encoding" для одномерного тензора, содержащего целые числа (длина вектора заранее неизвестна, набор значений заранее неизвестен, при этом в итоговой матрице должны присутствовать столбцы для всех натуральных чисел вплоть до максимального встречающегося в исходном массиве).

Пример:

для тензора `torch.tensor([2, 3, 2, 2, 2, 1])`.

Ожидается результат:

```python
tensor([[0., 1., 0.],
        [0., 0., 1.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [1., 0., 0.]])
```

In [864]:
ar1 = torch.tensor([2, 3, 2, 2, 2, 1])

x = ar1.max()
y = ar1.shape[0]
zeros = torch.zeros(y, x)
index = torch.cat((torch.arange(0, y).unsqueeze(1), ar1.unsqueeze(1) - 1), 1).type(torch.LongTensor)
index = index.chunk(y, dim = 1)

zeros[index] = 1
zeros

tensor([[0., 1., 0.],
        [0., 0., 1.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [1., 0., 0.]])

1.3.14 Создать тензор `arr` из 20 случайных целых чисел от 0 до 100. Найти самое частое значение в тензоре. 
Найти индексы в тензоре, соответствующие самому частому значению. Проверить, как работет алгоритм при двух значениях, имеющих наибольшую встречаемость, предложить приемлемое поведение алгоритма для этого случая. 

In [884]:
ar1 = torch.randint(0, 100, (1, 100))
counts = ar1.unique(return_counts = True)
counts = torch.cat((counts[0].unsqueeze(1), counts[1].unsqueeze(1)), 1)
counts

tensor([[ 1,  1],
        [ 2,  1],
        [ 3,  2],
        [ 7,  1],
        [ 8,  1],
        [11,  1],
        [12,  2],
        [13,  2],
        [15,  3],
        [16,  1],
        [17,  3],
        [24,  2],
        [25,  3],
        [27,  1],
        [28,  1],
        [29,  2],
        [30,  2],
        [31,  2],
        [32,  3],
        [36,  2],
        [37,  1],
        [38,  1],
        [39,  1],
        [41,  2],
        [45,  1],
        [47,  1],
        [49,  1],
        [53,  1],
        [54,  5],
        [55,  1],
        [56,  2],
        [59,  2],
        [60,  6],
        [61,  2],
        [62,  1],
        [63,  2],
        [64,  1],
        [66,  1],
        [67,  2],
        [72,  2],
        [73,  1],
        [76,  2],
        [77,  1],
        [78,  1],
        [80,  1],
        [81,  1],
        [83,  2],
        [84,  1],
        [86,  1],
        [87,  1],
        [88,  1],
        [89,  1],
        [90,  2],
        [94,  2],
        [96,  1],
        [9

torch.return_types.mode(
values=tensor(30),
indices=tensor(15))

torch.return_types.mode(
values=tensor(1),
indices=tensor(1))

## 1.4 Математические задачи

1.4.1 Приблизительно (с погрешностью порядка 1%) рассчитать на какой части интервала от 0 до 10 значение функции x * sin(x) больше 0.5.

In [650]:
tensor = torch.rand((1, 100)) * 10
function_tensor = tensor.sin() * tensor

torch.where(function_tensor > 0.5, torch.zeros(1,100), tensor).unique()[1:]

#по идее дальше нужно найти интервалы внутри полученного ряда и сгруппировать их

tensor([0.2943, 0.3270, 0.3868, 0.3984, 0.4083, 0.4538, 0.5556, 3.0836, 3.1070,
        3.1405, 3.1692, 3.1775, 3.4264, 3.5338, 3.7987, 3.8334, 3.9083, 3.9280,
        3.9600, 4.0531, 4.2481, 4.2679, 4.3929, 4.4878, 4.5502, 4.6898, 4.8267,
        5.0048, 5.1027, 5.1472, 5.1884, 5.2519, 5.3866, 5.3959, 5.4937, 5.6373,
        5.6794, 5.7757, 5.7947, 5.9605, 6.0418, 6.1575, 6.3050, 9.3773, 9.3877,
        9.4144, 9.5011, 9.6694, 9.6791, 9.7949, 9.8899, 9.9390])

tensor(0.5200)

1.4.2 Найти все простые числа в пределах ста. (Для решения предлагается использовать Решето Эратосфена) Использовать не более 1 цикла (желательно).

In [707]:
tensor = torch.arange(2, 101)
i = 2
while i < 100:
    tensor = torch.where(torch.isin(tensor, tensor * i), torch.zeros(tensor.shape), tensor).unique()
    i = i + 1

#заменим первый элемент с нуля на 1
tensor[0] = 1
tensor

tensor([ 1.,  2.,  3.,  5.,  7., 11., 13., 17., 19., 23., 29., 31., 37., 41.,
        43., 47., 53., 59., 61., 67., 71., 73., 79., 83., 89., 97.])

1.4.3 Найти евклидово расстояние между двумя одномерными тензорами одинаковой размерности, не используя готовые решения из библиотек.

In [709]:
#тут уже было решение, возможно потому что делали похожее на занятии?
a = torch.tensor([3, 4])
b = torch.tensor([0, 0])

def euclid_dist(a, b = None):
    if b is None:
        b = torch.zeros_like(a)
        
    return ((a - b) ** 2).sum(dim=-1) ** 0.5

euclid_dist(a, b)

tensor(5.)

1.4.4 Создать двумерный тензор 20 на 3, содержащий случайные целые числа от 0 до 100. 
Интерпретируя тензор как 20 векторов из 3х компонент, отсортировать его по длине векторов.

In [719]:
tensor = torch.randint(0, 101, (20, 3))

sort_indexes = torch.sum(tensor, 1).sort(dim = 0)[1]
tensor[sort_indexes]

tensor([[  6,  13,  53],
        [  8,  41,  27],
        [ 33,  39,  11],
        [  7,  20,  93],
        [ 70,  22,  40],
        [ 70,  14,  56],
        [ 60,  67,  20],
        [ 74,  15,  62],
        [ 82,  78,   1],
        [ 65,  70,  27],
        [ 75,  46,  43],
        [ 96,  72,   5],
        [ 94,  51,  30],
        [ 24,  61,  90],
        [ 24,  68,  92],
        [ 75,  25,  98],
        [100,  15,  98],
        [ 99,  25,  94],
        [ 94,  59,  78],
        [ 82,  97,  83]])

1.4.5 Найти "локальные максимумы" в одномерном тензоре (т.е. значения, большие предыдущего и последующего) `torch.tensor([1, 3, 7, 1, 2, 6, 0, 1])` и вывести их индексы.

In [790]:
tensor = torch.tensor([1, 3, 7, 1, 2, 6, 0, 1])
first_max = torch.maximum(tensor[:-1], tensor[1 :])
second_max = torch.maximum(first_max[:-1], first_max[1 :])
local_maxs = second_max.unique()

for value in local_maxs:
    print((tensor == value).nonzero(as_tuple=True)[0])

tensor([5])
tensor([2])


1.4.6 Задан произвольный массив numpy (например массив из 100 случайных числе от 0 до 1). Необходимо найти в нем число наиболее близкое к заданному.

In [798]:
arr = np.linspace(0, 1, 100)
print(arr)
given_value = 0.456

index = numpy.searchsorted(arr, given_value, side='left', sorter=None)
arr[index]

[0.         0.01010101 0.02020202 0.03030303 0.04040404 0.05050505
 0.06060606 0.07070707 0.08080808 0.09090909 0.1010101  0.11111111
 0.12121212 0.13131313 0.14141414 0.15151515 0.16161616 0.17171717
 0.18181818 0.19191919 0.2020202  0.21212121 0.22222222 0.23232323
 0.24242424 0.25252525 0.26262626 0.27272727 0.28282828 0.29292929
 0.3030303  0.31313131 0.32323232 0.33333333 0.34343434 0.35353535
 0.36363636 0.37373737 0.38383838 0.39393939 0.4040404  0.41414141
 0.42424242 0.43434343 0.44444444 0.45454545 0.46464646 0.47474747
 0.48484848 0.49494949 0.50505051 0.51515152 0.52525253 0.53535354
 0.54545455 0.55555556 0.56565657 0.57575758 0.58585859 0.5959596
 0.60606061 0.61616162 0.62626263 0.63636364 0.64646465 0.65656566
 0.66666667 0.67676768 0.68686869 0.6969697  0.70707071 0.71717172
 0.72727273 0.73737374 0.74747475 0.75757576 0.76767677 0.77777778
 0.78787879 0.7979798  0.80808081 0.81818182 0.82828283 0.83838384
 0.84848485 0.85858586 0.86868687 0.87878788 0.88888889 0.89898

0.4646464646464647

1.4.7 Решить матричное уравнение `A*X*B=-C` - найти матрицу X. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [817]:
A = torch.tensor([[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]])
B = torch.tensor([[3, -1], [2, 1]])
C = torch.tensor([[7, 21], [11, 8], [8, 4]])



RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x3 and 2x2)

In [304]:
X

tensor([[ 1.0000e+00,  5.9605e-08],
        [-2.0000e+00,  1.0000e+00],
        [ 3.0000e+00, -4.0000e+00]])

In [307]:
-C

tensor([[ -7., -21.],
        [-11.,  -8.],
        [ -8.,  -4.]])

In [305]:
A @ X @ B

tensor([[ -7.0000, -21.0000],
        [-11.0000,  -8.0000],
        [ -8.0000,  -4.0000]])

1.4.8 Проверить, является ли система векторов a1 = (3; −3; 0; 7),
a2 = (2; 2; 4; 7), a3 = (1; 2; 3; 4), a4 = (5; −4; 1; 3) линейно зависимой?

tensor(4.0457e-14, dtype=torch.float64)

1.4.9 Сгенирировать тензор из 200 случайных целых чисел, нормально распрделенных cо стандартным отклонением $\sigma = 10$ и матожиданием $\mu = 0$. Построить тензор гистограммы с 20 бинами. 

(tensor(9.3921), tensor(0.0670))

torch.return_types.histogram(
hist=tensor([ 1.,  0.,  0.,  2.,  4.,  1.,  7.,  9., 27., 24., 14., 26., 27., 19.,
        16.,  9.,  7.,  5.,  0.,  2.]),
bin_edges=tensor([-33.0306, -30.0873, -27.1440, -24.2007, -21.2574, -18.3141, -15.3708,
        -12.4275,  -9.4842,  -6.5409,  -3.5976,  -0.6543,   2.2890,   5.2323,
          8.1756,  11.1189,  14.0623,  17.0056,  19.9489,  22.8922,  25.8355]))